export default [
 "Servicio de Salud Metropolitano Sur",
 //"-",
 "Servicio de Salud Ñuble",
 "Test",
 "Servicio de Salud Chiloé",
 "Servicio de Salud Araucanía Sur",
 "Servicio de Salud Antofagasta",
 "Servicio de Salud Del Maule",
 "SEREMI Metropolitana de Santiago",
 "Servicio de Salud Los Ríos",
 "Servicio de Salud Coquimbo",
 "Servicio de Salud Iquique",
 "Servicio de Salud Talcahuano",
 "Servicio de Salud Aconcagua",
 "Servicio de Salud Metropolitano Central",
 "Servicio de Salud Arica",
 "Servicio de Salud Concepción",
 "Servicio de Salud Arauco",
 "Servicio de Salud Aisén",
 "Servicio de Salud Metropolitano Sur Oriente",
 "Servicio de Salud Araucanía Norte",
 "Servicio de Salud Biobío",
 "Servicio de Salud Magallanes",
 "Servicio de Salud Atacama",
 "Servicio de Salud Del Reloncaví",
 "[DELETED]",
 "Servicio de Salud Metropolitano Norte",
 "Servicio de Salud Del Libertador B.O'Higgins",
 "Servicio de Salud Metropolitano Occidente",
 "Servicio de Salud Viña del Mar Quillota",
 "Servicio de Salud Valparaíso San Antonio",
 "Servicio de Salud Metropolitano Oriente",
 "Servicio de Salud Osorno",
]
